# Generated by Django 3.2.16 on 2022-11-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=155, unique=True)),
                ('social_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('driving_license', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('citizen_status', models.CharField(blank=True, choices=[('Permanent resident', 'Permanent'), ('Temporary resident', 'Temporaire'), ('Canadian citizen', 'Canadien'), ('Refugie', 'Refugie')], default='Permanent resident', max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=50, null=True)),
                ('profile_image', models.ImageField(blank=True, default='noimage', null=True, upload_to='uploads/UserImage')),
                ('street_number', models.CharField(blank=True, max_length=10, null=True)),
                ('street_name', models.CharField(blank=True, default='Canada', max_length=155, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=155, null=True)),
                ('metro_location', models.CharField(max_length=155)),
                ('town', models.CharField(blank=True, default='Montréal', max_length=155, null=True)),
                ('province', models.CharField(blank=True, default='Québec', max_length=155, null=True)),
                ('country', models.CharField(blank=True, default='Canada', max_length=155, null=True)),
                ('accept_tnc', models.BooleanField(default=True)),
                ('is_worker', models.BooleanField(default=False)),
                ('is_job_owner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
